#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-xpath
Version  : 2.0.0
Release  : 5
URL      : https://rubygems.org/downloads/xpath-2.0.0.gem
Source0  : https://rubygems.org/downloads/xpath-2.0.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-disposable
BuildRequires : rubygem-mini_portile
BuildRequires : rubygem-nokogiri
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-yard

%description
# XPath
XPath is a Ruby DSL around a subset of XPath 1.0. Its primary purpose is to
facilitate writing complex XPath queries from Ruby code.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n xpath-2.0.0
gem spec %{SOURCE0} -l --ruby > rubygem-xpath.gemspec

%build
gem build rubygem-xpath.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
xpath-2.0.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/xpath-2.0.0
rspec -I.:lib spec/ || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/xpath-2.0.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/ExpressionLevel/%26-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/ExpressionLevel/%2b-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/ExpressionLevel/%3d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/ExpressionLevel/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/ExpressionLevel/%7c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/ExpressionLevel/%7e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/ExpressionLevel/and-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/ExpressionLevel/cdesc-ExpressionLevel.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/ExpressionLevel/equals-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/ExpressionLevel/inverse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/ExpressionLevel/is-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/ExpressionLevel/n-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/ExpressionLevel/normalize-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/ExpressionLevel/one_of-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/ExpressionLevel/or-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/ExpressionLevel/string_literal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/ExpressionLevel/union-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/ExpressionLevel/where-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/TopLevel/anywhere-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/TopLevel/attr-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/TopLevel/axis-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/TopLevel/cdesc-TopLevel.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/TopLevel/child-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/TopLevel/contains-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/TopLevel/css-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/TopLevel/current-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/TopLevel/descendant-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/TopLevel/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/TopLevel/next_sibling-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/TopLevel/previous_sibling-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/TopLevel/starts_with-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/TopLevel/string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/TopLevel/text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/DSL/cdesc-DSL.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Expression/arguments-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Expression/cdesc-Expression.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Expression/current-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Expression/expression-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Expression/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Expression/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Expression/to_xpath-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/HTML/button-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/HTML/cdesc-HTML.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/HTML/checkbox-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/HTML/definition_description-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/HTML/field-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/HTML/fieldset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/HTML/file_field-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/HTML/fillable_field-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/HTML/link-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/HTML/link_or_button-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/HTML/locate_field-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/HTML/optgroup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/HTML/option-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/HTML/radio_button-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/HTML/select-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/HTML/table-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Literal/cdesc-Literal.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Literal/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Literal/value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/and-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/anywhere-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/attribute-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/axis-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/cdesc-Renderer.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/child-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/contains-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/convert_argument-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/css-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/descendant-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/equality-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/inverse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/is-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/literal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/next_sibling-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/node_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/normalized_space-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/one_of-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/or-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/previous_sibling-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/render-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/starts_with-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/string_function-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/string_literal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/this_node-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/union-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/variable-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Renderer/where-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Union/arguments-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Union/cdesc-Union.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Union/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Union/expression-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Union/expressions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Union/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Union/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Union/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/Union/to_xpath-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/cdesc-XPath.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/XPath/generate-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/xpath-2.0.0/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/gems/xpath-2.0.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/xpath-2.0.0/lib/xpath.rb
/usr/lib64/ruby/gems/2.2.0/gems/xpath-2.0.0/lib/xpath/dsl.rb
/usr/lib64/ruby/gems/2.2.0/gems/xpath-2.0.0/lib/xpath/expression.rb
/usr/lib64/ruby/gems/2.2.0/gems/xpath-2.0.0/lib/xpath/html.rb
/usr/lib64/ruby/gems/2.2.0/gems/xpath-2.0.0/lib/xpath/literal.rb
/usr/lib64/ruby/gems/2.2.0/gems/xpath-2.0.0/lib/xpath/renderer.rb
/usr/lib64/ruby/gems/2.2.0/gems/xpath-2.0.0/lib/xpath/union.rb
/usr/lib64/ruby/gems/2.2.0/gems/xpath-2.0.0/lib/xpath/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/xpath-2.0.0/spec/fixtures/form.html
/usr/lib64/ruby/gems/2.2.0/gems/xpath-2.0.0/spec/fixtures/simple.html
/usr/lib64/ruby/gems/2.2.0/gems/xpath-2.0.0/spec/fixtures/stuff.html
/usr/lib64/ruby/gems/2.2.0/gems/xpath-2.0.0/spec/html_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/xpath-2.0.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/xpath-2.0.0/spec/union_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/xpath-2.0.0/spec/xpath_spec.rb
/usr/lib64/ruby/gems/2.2.0/specifications/xpath-2.0.0.gemspec
